# Use the Ruby 3.2.2 image from Docker Hub as the base image (https://hub.docker.com/_/ruby)
FROM ruby:3.2.2

RUN ls /etc
RUN apt update -qq && apt install -y postgresql-client git libvips curl cron vim libgeos-dev
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt install nodejs
RUN npm install --global yarn

WORKDIR /app

# Add Rails gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

RUN bundle install

COPY . .

# Build and deploy React front-end
RUN yarn config set network-timeout 600000 -g
RUN yarn build && yarn deploy

# Clean up APT when done.
RUN apt clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Create cron log file
RUN touch cron.log

RUN chmod +x ./ecds-entrypoint.sh

EXPOSE 3000 8108

ENTRYPOINT [ "./ecds-entrypoint.sh" ]